name: Mirror LOGGER

on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * 0'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Mirror Repository
      run: |
        git clone "https://github.com/Marc-Bernard-Tools/Mirror-LOGGER.git"
        ls -l
        bash scripts/credits.sh scripts/credits-logger.txt Mirror-LOGGER/src
        bash scripts/descriptions.sh Mirror-LOGGER/src
        rm src/log/#mbtools#*
        cp Mirror-LOGGER/src/#mbtools#* src/log/
        rm -rf Mirror-LOGGER
        git status
    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v5
      if: github.repository == 'Marc-Bernard-Tools/MBT-Package-Manager'
      with:
        node-version: 20
        branch: mbtools/logger
        title: Automatic Update LOGGER
        body: |
          Automatic update from mirror
          https://github.com/Marc-Bernard-Tools/Mirror-LOGGER
