name: Mirror STRINGMAP

on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * 0'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Mirror Repository
      run: |
        git clone "https://github.com/Marc-Bernard-Tools/Mirror-STRINGMAP.git"
        ls -l
        bash scripts/credits.sh scripts/credits-stringmap.txt Mirror-STRINGMAP/src
        bash scripts/descriptions.sh Mirror-STRINGMAP/src
        rm src/stringmap/#mbtools#*
        cp Mirror-STRINGMAP/src/#mbtools#* src/stringmap/
        rm -rf Mirror-STRINGMAP
        git status
    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v5
      if: github.repository == 'Marc-Bernard-Tools/MBT-Base'
      with:
        branch: mbtools/stringmap
        title: Automatic Update STRINGMAP
        body: |
          Automatic update from mirror
          https://github.com/Marc-Bernard-Tools/Mirror-STRINGMAP
